version: '{build}'
image:
  - Visual Studio 2019
  - Ubuntu
skip_commits:
  files:
    - '*.md'
    - '*.txt'
    - 'run.*'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
  except:
    - /.+[\-.]wip$/
    - wip
skip_tags: true
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
- cmd: curl -sSLO https://dot.net/v1/dotnet-install.ps1
- ps: if ($isWindows) { ./dotnet-install.ps1 -JsonFile global.json }
- sh: curl -sSLO https://dot.net/v1/dotnet-install.sh
- sh: chmod +x dotnet-install.sh
- sh: ./dotnet-install.sh --jsonfile global.json
- sh: export PATH="$HOME/.dotnet:$PATH"
before_build:
- dotnet --info
build_script:
- ps: |-
    $id = ([datetimeoffset]$env:APPVEYOR_REPO_COMMIT_TIMESTAMP).ToUniversalTime().ToString('yyyyMMdd''t''HHmm')
    if ($isWindows) { .\pack.cmd ci-$id } else { ./pack.sh ci-$id }
artifacts:
- path: dist\*.nupkg
- path: dist\*.snupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
